language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - master

sudo: false

matrix:
  allow_failures:
    - go: master

dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats

before_install:
  - wget https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz
  - tar xzvf gometalinter-2.0.5-linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/gometalinter-2.0.5-linux-amd64:$PWD/gometalinter-2.0.5-linux-amd64/linters
  - go get github.com/mattn/goveralls

install:
  - make goget

script:
  - make checktest
  - make checkmeta
  - make checkbats

after_success:
  - echo "$TRAVIS_GO_VERSION"
  - test "$TRAVIS_GO_VERSION" = "1.10" && $GOPATH/bin/goveralls -service=travis-ci -debug

notifications:
  email:
    on_failure: always
    on_success: change
