name: Go CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16]
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Go ${{ matrix.go }} @ ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - run: go version
