---
name: Go CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.11', '1.12', '1.13', '1.14', '1.15', '1.16']
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Go ${{ matrix.go-version }} @ ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go version
          go build -v ./...
          go test -v -race ./...
      - uses: golangci/golangci-lint-action@v2
        with:
          args: --sort-results --verbose ./...
      - name: Bats (!= windows-latest)
        if: matrix.os != 'windows-latest'
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          npm install --global bats@1.3.0
          ~/.npm-global/bin/bats bats/
